name: Build, Deploy and Manage Workflow

on:
  push:
    branches:
      - podman
  workflow_dispatch:

env:
  WORKFLOW_IMAGE_REGISTRY: ghcr.io
  WORKFLOW_IMAGE_NAMESPACE: ${{ github.repository_owner }}
  TARGET_NS: ${{ secrets.TARGET_NAMESPACE }}
  MANIFESTS_DIR: manifests/${{ github.sha }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-workflow:
    name: Build and Push Workflow Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # STEP 1: Debug entire repository structure
      - name: Debug: List all files in the repo
        run: |
          echo "DEBUG: Listing entire repository contents..."
          ls -R

      # STEP 2: Debug environment variables
      - name: Debug Environment Variables
        run: |
          echo "DEBUG: Checking Environment Variables..."
          echo "GITHUB_WORKSPACE='${GITHUB_WORKSPACE}'"
          echo "WORKFLOW_FOLDER='${{ secrets.WORKFLOW_FOLDER }}' (masked if it's a secret)"

      - name: Validate Environment Variables
        run: |
          echo "Validating required variables..."
          REQUIRED_VARS=("WORKFLOW_IMAGE_REGISTRY" "WORKFLOW_IMAGE_NAMESPACE" "GITHUB_SHA" "TARGET_NS")

          if [[ -z "${{ secrets.WORKFLOW_FOLDER }}" ]]; then
            echo "::error:: WORKFLOW_FOLDER is not set in GitHub Secrets. Please configure it."
            exit 1
          fi
          echo "WORKFLOW_FOLDER=${{ secrets.WORKFLOW_FOLDER }}" >> $GITHUB_ENV

          MISSING_VARS=()
          for var in "${REQUIRED_VARS[@]}"; do
            if [[ -z "${!var}" ]]; then
              MISSING_VARS+=("$var")
            fi
          done

          if [[ ${#MISSING_VARS[@]} -gt 0 ]]; then
            echo "::error:: The following required variables are missing:"
            printf "::error:: - %s\n" "${MISSING_VARS[@]}"
            exit 1
          fi

      - name: Extract Workflow ID and Path
        run: |
          echo "DEBUG: Checking and setting WORKFLOW_PATH..."

          WORKFLOW_FOLDER="${{ secrets.WORKFLOW_FOLDER }}"
          if [[ -z "$WORKFLOW_FOLDER" ]]; then
            echo "::error:: WORKFLOW_FOLDER is not set in GitHub Secrets! Exiting."
            exit 1
          fi

          WORKFLOW_PATH="${GITHUB_WORKSPACE}/${WORKFLOW_FOLDER}"
          WORKFLOW_ID=$(basename "$WORKFLOW_FOLDER")

          echo "Resolved WORKFLOW_PATH=${WORKFLOW_PATH}"
          echo "WORKFLOW_PATH=${WORKFLOW_PATH}" >> $GITHUB_ENV
          echo "WORKFLOW_ID=${WORKFLOW_ID}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${WORKFLOW_IMAGE_REGISTRY}/${WORKFLOW_IMAGE_NAMESPACE}/demo-${WORKFLOW_ID}" >> $GITHUB_ENV

          echo "Checking if workflow folder exists..."
          if [[ ! -d "$WORKFLOW_PATH" ]]; then
            echo "::error:: WORKFLOW_FOLDER '${WORKFLOW_FOLDER}' does not exist in the repository!"
            echo "Expected path: $WORKFLOW_PATH"
            ls -l ${GITHUB_WORKSPACE}
            exit 1
          fi

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Log in to Red Hat Container Registry
        run: |
          echo "${{ secrets.REDHAT_REGISTRY_PASSWORD }}" | podman login registry.redhat.io -u ${{ secrets.REDHAT_REGISTRY_USERNAME }} --password-stdin

      - name: Log in to GitHub Container Registry (GHCR)
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      # STEP 3: Debug what's inside WORKFLOW_FOLDER & WF_RESOURCES before building
      - name: Debug: Show WORKFLOW_FOLDER & WF_RESOURCES
        run: |
          echo "WORKFLOW_FOLDER='${{ env.WORKFLOW_FOLDER }}' (masked if secret)"
          WF_RESOURCES="${GITHUB_WORKSPACE}/${{ env.WORKFLOW_FOLDER }}/src/main/resources"
          echo "WF_RESOURCES=$WF_RESOURCES"

          echo "Contents of $GITHUB_WORKSPACE/${{ env.WORKFLOW_FOLDER }}:"
          ls -l $GITHUB_WORKSPACE/${{ env.WORKFLOW_FOLDER }} || true

          echo "Contents of $WF_RESOURCES:"
          ls -l $WF_RESOURCES || true

      - name: Build and Push Image to GHCR
        run: |
          WF_RESOURCES="${GITHUB_WORKSPACE}/${WORKFLOW_FOLDER}/src/main/resources"

          if [[ ! -d "$WF_RESOURCES" ]]; then
            echo "::error:: The directory '$WF_RESOURCES' does not exist! Check your WORKFLOW_FOLDER setting."
            echo "Available directories under ${GITHUB_WORKSPACE}/${WORKFLOW_FOLDER}:"
            ls -l ${GITHUB_WORKSPACE}/${WORKFLOW_FOLDER} || true
            exit 1
          fi

          echo "Using WF_RESOURCES=$WF_RESOURCES"

          podman build -f resources/workflow-builder.Dockerfile \
            --build-arg WF_RESOURCES=${WF_RESOURCES} \
            --build-arg FLOW_NAME="${WORKFLOW_ID}" \
            --build-arg FLOW_SUMMARY="Workflow ${WORKFLOW_ID}" \
            --build-arg FLOW_DESCRIPTION="Automated workflow deployment for ${WORKFLOW_ID}" \
            --ulimit nofile=4096:4096 \
            --tag ${IMAGE_NAME}:${IMAGE_TAG} \
            --tag ${IMAGE_NAME}:latest .

          podman push ${IMAGE_NAME}:${IMAGE_TAG}
          podman push ${IMAGE_NAME}:latest

      - name: Make Image Public
        run: |
          IMAGE_REPO=$(echo "${IMAGE_NAME}" | sed 's|ghcr.io/||')
          curl -X PATCH https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/${IMAGE_REPO}/visibility \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"visibility":"public"}'

  generate-manifests:
    name: Generate OpenShift Manifests
    runs-on: ubuntu-latest
    needs: build-workflow

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Required CLI Tools
        run: |
          sudo apt update
          sudo apt install -y yq jq
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvzf oc.tar.gz
          sudo mv oc /usr/local/bin/
          curl -LO https://downloads.kogito.kie.org/tools/kn-workflow-cli/latest/kn-workflow-linux-amd64
          chmod +x kn-workflow-linux-amd64
          sudo mv kn-workflow-linux-amd64 /usr/local/bin/kn-workflow

      - name: Generate OpenShift Manifests
        run: |
          mkdir -p ${MANIFESTS_DIR}
          cd ${WORKFLOW_PATH}/src/main/resources
          echo -e "\nquarkus.flyway.migrate-at-start=true" >> application.properties
          kn-workflow gen-manifest

      - name: Commit Updated Manifests
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout ${{ github.ref_name }}
          git add ${MANIFESTS_DIR}/*
          git commit -m "Updating OpenShift manifests for workflow ${WORKFLOW_ID} [GitHub Actions]" || echo "No changes to commit"
          git push origin ${{ github.ref_name }}

  deploy-to-openshift:
    name: Deploy to OpenShift
    runs-on: ubuntu-latest
    needs: generate-manifests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OpenShift CLI (oc)
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvzf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Log in to OpenShift
        run: |
          oc login --server=${{ secrets.OCP_API_SERVER }} --token=${{ secrets.OCP_API_TOKEN }} --insecure-skip-tls-verify=true

      - name: Apply OpenShift Manifests
        run: |
          TARGET_NS=${{ secrets.TARGET_NAMESPACE }}
          oc apply -f ${MANIFESTS_DIR} -n $TARGET_NS
