name: Build, Deploy and Manage Workflow

on:
  push:
    branches:
      - podman
  workflow_dispatch:

env:
  WORKFLOW_IMAGE_REGISTRY: ghcr.io
  WORKFLOW_IMAGE_NAMESPACE: ${{ github.repository_owner }}
  TARGET_NS: ${{ secrets.TARGET_NAMESPACE }}
  MANIFESTS_DIR: manifests/${{ github.sha }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-workflow:
    name: Build and Push Workflow Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug: List all files in the repo
        run: |
          echo "DEBUG: Listing repository contents..."
          ls -R ${GITHUB_WORKSPACE}

      - name: Debug Environment Variables
        run: |
          echo "DEBUG: Checking Environment Variables..."
          echo "GITHUB_WORKSPACE='${GITHUB_WORKSPACE}'"
          echo "WORKFLOW_FOLDER='${{ secrets.WORKFLOW_FOLDER }}'"

      - name: Validate Environment Variables
        run: |
          echo "Validating required variables..."
          REQUIRED_VARS=("WORKFLOW_IMAGE_REGISTRY" "WORKFLOW_IMAGE_NAMESPACE" "GITHUB_SHA" "TARGET_NS")

          if [[ -z "${{ secrets.WORKFLOW_FOLDER }}" ]]; then
            echo "::error:: WORKFLOW_FOLDER is not set in GitHub Secrets. Please configure it."
            exit 1
          fi
          echo "WORKFLOW_FOLDER=${{ secrets.WORKFLOW_FOLDER }}" >> $GITHUB_ENV

          MISSING_VARS=()
          for var in "${REQUIRED_VARS[@]}"; do
            if [[ -z "${!var}" ]]; then
              MISSING_VARS+=("$var")
            fi
          done

          if [[ ${#MISSING_VARS[@]} -gt 0 ]]; then
            echo "::error:: The following required variables are missing:"
            printf "::error:: - %s\n" "${MISSING_VARS[@]}"
            exit 1
          fi

      - name: Extract Workflow ID and Path
        run: |
          echo "DEBUG: Checking and setting WORKFLOW_PATH..."
          
          WORKFLOW_FOLDER="${{ secrets.WORKFLOW_FOLDER }}"
          if [[ -z "$WORKFLOW_FOLDER" ]]; then
            echo "::error:: WORKFLOW_FOLDER is not set in GitHub Secrets! Exiting."
            exit 1
          fi

          WORKFLOW_PATH="${GITHUB_WORKSPACE}/${WORKFLOW_FOLDER}"
          WORKFLOW_ID=$(basename "$WORKFLOW_FOLDER")

          echo "Resolved WORKFLOW_PATH=${WORKFLOW_PATH}"
          echo "WORKFLOW_PATH=${WORKFLOW_PATH}" >> $GITHUB_ENV
          echo "WORKFLOW_ID=${WORKFLOW_ID}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${WORKFLOW_IMAGE_REGISTRY}/${WORKFLOW_IMAGE_NAMESPACE}/demo-${WORKFLOW_ID}" >> $GITHUB_ENV

          echo "Checking if workflow folder exists..."
          if [[ ! -d "$WORKFLOW_PATH" ]]; then
            echo "::error:: WORKFLOW_FOLDER '${WORKFLOW_FOLDER}' does not exist in the repository!"
            echo "Expected path: $WORKFLOW_PATH"
            ls -l ${GITHUB_WORKSPACE}
            exit 1
          fi

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Log in to Red Hat Container Registry
        run: |
          echo "${{ secrets.REDHAT_REGISTRY_PASSWORD }}" | podman login registry.redhat.io -u ${{ secrets.REDHAT_REGISTRY_USERNAME }} --password-stdin

      - name: Log in to GitHub Container Registry (GHCR)
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Detect and Set Correct `WF_RESOURCES`
        run: |
          echo "DEBUG: Detecting the correct path for workflow resources..."

          WF_RESOURCES=""

          if [[ -d "${GITHUB_WORKSPACE}/${WORKFLOW_FOLDER}/src/main/resources" ]]; then
            WF_RESOURCES="${GITHUB_WORKSPACE}/${WORKFLOW_FOLDER}/src/main/resources"
          elif [[ -d "${GITHUB_WORKSPACE}/${WORKFLOW_FOLDER}/resources" ]]; then
            WF_RESOURCES="${GITHUB_WORKSPACE}/${WORKFLOW_FOLDER}/resources"
          fi

          if [[ -z "$WF_RESOURCES" ]]; then
            echo "::error:: The directory for workflow resources could not be found!"
            echo "Checked paths:"
            echo " - ${GITHUB_WORKSPACE}/${WORKFLOW_FOLDER}/src/main/resources"
            echo " - ${GITHUB_WORKSPACE}/${WORKFLOW_FOLDER}/resources"
            exit 1
          fi

          echo "Final WF_RESOURCES path: $WF_RESOURCES"
          echo "WF_RESOURCES=$WF_RESOURCES" >> $GITHUB_ENV

      - name: Build and Push Image to GHCR
        run: |
          podman build -f resources/workflow-builder.Dockerfile \
            --build-arg WF_RESOURCES=${WF_RESOURCES} \
            --build-arg FLOW_NAME="${WORKFLOW_ID}" \
            --build-arg FLOW_SUMMARY="Workflow ${WORKFLOW_ID}" \
            --build-arg FLOW_DESCRIPTION="Automated workflow deployment for ${WORKFLOW_ID}" \
            --ulimit nofile=4096:4096 \
            --tag ${IMAGE_NAME}:${IMAGE_TAG} \
            --tag ${IMAGE_NAME}:latest .

          podman push ${IMAGE_NAME}:${IMAGE_TAG}
          podman push ${IMAGE_NAME}:latest

      - name: Make Image Public
        run: |
          IMAGE_REPO=$(echo "${IMAGE_NAME}" | sed 's|ghcr.io/||')
          curl -X PATCH https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/${IMAGE_REPO}/visibility \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"visibility":"public"}'

